# Generated by Django 5.0.6 on 2024-07-23 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_alter_orderitems_order_alter_product_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitems",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="main.product"
            ),
        ),
    ]
