# Generated by Django 5.0.6 on 2024-07-24 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0007_rename_orderitems_orderitem"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="OrderItem",
            new_name="OrderItems",
        ),
        migrations.AlterField(
            model_name="order",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customer_orders",
                to="main.customer",
            ),
        ),
    ]
